export { CouponParseService } from './coupon-parse.service';
export { RetailerService } from './retailer.service';
export { DictionaryService } from './dictionary.service';
export { UserService } from './user.service';
export { DataParseService } from './data-parse.service';
export { CloudinaryService } from './cloudinary.service'
export { MailService } from './mail.service';
export { PlatformService } from './platform.service';
export { CouponService } from './coupon.service';
export { MapRetailerToAdmitadFeedService } from './map-retailer-admitad-feed.service';
export { RetailerOnPlatformService } from './retailer-on-platform.service';
export { ContentManagerService } from './content-manager.service';
